#!/bin/bash
# Activate toolkit virtual environment
if [ -f "$HOME/.linux-toolkit-activate" ]; then
    source "$HOME/.linux-toolkit-activate"
fi

# ============================================================
# Aliases Manager - Setup useful aliases for the toolkit
# ============================================================

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
ALIAS_FILE="$HOME/.bashrc_aliases"
BACKUP_DIR="$HOME/.alias_backups"

# Function to show usage
usage() {
    echo "Usage: $0 [options]"
    echo ""
    echo "Options:"
    echo "  -i, --install     Install aliases to .bashrc"
    echo "  -r, --remove      Remove toolkit aliases"
    echo "  -l, --list        List available aliases"
    echo "  -s, --show        Show currently installed aliases"
    echo "  -b, --backup      Backup current .bashrc"
    echo "  -h, --help        Show this help message"
    exit 0
}

# Function to backup .bashrc
backup_bashrc() {
    mkdir -p "$BACKUP_DIR"
    local backup_file="$BACKUP_DIR/bashrc_backup_$(date +%Y%m%d_%H%M%S)"
    
    if [ -f "$HOME/.bashrc" ]; then
        cp "$HOME/.bashrc" "$backup_file"
        echo -e "${GREEN}✓ .bashrc backed up to: $backup_file${NC}"
    else
        echo -e "${YELLOW}No .bashrc file found to backup${NC}"
    fi
}

# Function to create aliases file
create_aliases_file() {
    cat > "$ALIAS_FILE" << 'EOF'
# ==============================================
# Linux Toolkit Aliases
# Generated by aliases.sh
# ==============================================

# System Monitoring
alias sysmon='~/.local/bin/system_monitor.sh'
alias sysinfo='~/.local/bin/system_info.py'
alias psmon='~/.local/bin/process_manager.sh'
alias h='history'
alias paths='echo $PATH | tr ":" "\n"'

# Backup and Recovery
alias backup='~/.local/bin/backup_manager.sh'
alias backup-full='~/.local/bin/backup_manager.sh -t full'
alias backup-inc='~/.local/bin/backup_manager.sh -t incremental'
alias backup-list='~/.local/bin/backup_manager.sh --list'

# Security
alias security='sudo ~/.local/bin/security_audit.sh'
alias ports='sudo ~/.local/bin/security_audit.sh -p'
alias failed-logins='sudo ~/.local/bin/security_audit.sh -f'
alias audit='sudo ~/.local/bin/security_audit.sh -h'

# Log Analysis
alias logs='~/.local/bin/log_analyzer.sh'
alias log-error='~/.local/bin/log_analyzer.sh -e'
alias log-warn='~/.local/bin/log_analyzer.sh -w'
alias log-viz='~/.local/bin/log_visualizer.py'
alias syslog='~/.local/bin/log_analyzer.sh /var/log/syslog'

# User Management
alias users='sudo ~/.local/bin/user_manager.sh'
alias user-list='sudo ~/.local/bin/user_manager.sh -l'
alias user-add='sudo ~/.local/bin/user_manager.sh -a'
alias user-del='sudo ~/.local/bin/user_manager.sh -d'

# Network
alias netscan='~/.local/bin/network_scanner.sh'
alias netmon='~/.local/bin/network_monitor.py'
alias netstat='ss -tulpn'
alias myip='curl -s ifconfig.me'
alias portscan='sudo ~/.local/bin/network_scanner.sh -t full'

# Disk Management
alias diskclean='~/.local/bin/disk_cleaner.sh'
alias diskusage='~/.local/bin/disk_usage_analyzer.py'
alias df='df -h'
alias du='du -sh'
alias largest='find . -type f -exec du -h {} + | sort -rh | head -20'

# File Management
alias organizer='~/.local/bin/file_organizer.py'
alias organize-dl='~/.local/bin/file_organizer.py ~/Downloads -m type -r'
alias tree='tree -C'
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Directory Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ~='cd ~'
alias -- -='cd -'

# Process Management
alias pskill='~/.local/bin/process_manager.sh -k'
alias pstree='pstree -p'
alias memtop='ps aux --sort=-%mem | head -20'
alias cputop='ps aux --sort=-%cpu | head -20'

# System Information
alias kernel='uname -r'
alias osinfo='lsb_release -a'
alias uptime='uptime -p'
alias meminfo='free -h'
alias cpuinfo='lscpu'
alias disk-info='df -h'
alias systemd-analyze='systemd-analyze blame'

# Package Management
alias update='sudo apt update && sudo apt upgrade -y'
alias install='sudo apt install'
alias remove='sudo apt remove'
alias search='apt search'
alias autoremove='sudo apt autoremove -y'

# Log viewing shortcuts
alias journal='journalctl -xe'
alias dmesg='dmesg | tail -50'
alias authlog='sudo tail -f /var/log/auth.log'
alias syslog-tail='tail -f /var/log/syslog'

# Service Management
alias service-start='sudo systemctl start'
alias service-stop='sudo systemctl stop'
alias service-restart='sudo systemctl restart'
alias service-status='sudo systemctl status'
alias service-enable='sudo systemctl enable'
alias service-disable='sudo systemctl disable'

# Git shortcuts
alias gst='git status'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gcm='git commit -m'
alias gaa='git add -A'
alias gp='git push'
alias gl='git pull'
alias gd='git diff'

# Docker shortcuts (if installed)
alias dps='docker ps'
alias di='docker images'
alias dexec='docker exec -it'
alias dlogs='docker logs -f'

# End Linux Toolkit Aliases
EOF
    
    echo -e "${GREEN}✓ Aliases file created at: $ALIAS_FILE${NC}"
}

# Function to install aliases
install_aliases() {
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}        INSTALLING ALIASES${NC}"
    echo -e "${BLUE}========================================${NC}\n"
    
    # Backup existing .bashrc
    backup_bashrc
    
    # Create aliases file
    create_aliases_file
    
    # Check if aliases already sourced in .bashrc
    if grep -q "source ~/.bashrc_aliases" "$HOME/.bashrc" 2>/dev/null; then
        echo -e "${YELLOW}Aliases already sourced in .bashrc${NC}"
    else
        echo -e "\n# Source Linux Toolkit aliases" >> "$HOME/.bashrc"
        echo "if [ -f ~/.bashrc_aliases ]; then" >> "$HOME/.bashrc"
        echo "    source ~/.bashrc_aliases" >> "$HOME/.bashrc"
        echo "fi" >> "$HOME/.bashrc"
        echo -e "${GREEN}✓ Aliases added to .bashrc${NC}"
    fi
    
    # Source the aliases in current session
    source "$ALIAS_FILE"
    
    echo -e "\n${GREEN}✓ Aliases installed successfully!${NC}"
    echo -e "${YELLOW}To use aliases in current terminal, run: source ~/.bashrc${NC}"
}

# Function to remove aliases
remove_aliases() {
    echo -e "${YELLOW}Removing Linux Toolkit aliases...${NC}"
    
    # Remove from .bashrc
    if [ -f "$HOME/.bashrc" ]; then
        sed -i '/# Source Linux Toolkit aliases/,+3d' "$HOME/.bashrc"
        echo -e "${GREEN}✓ Removed alias sourcing from .bashrc${NC}"
    fi
    
    # Remove aliases file
    if [ -f "$ALIAS_FILE" ]; then
        rm -f "$ALIAS_FILE"
        echo -e "${GREEN}✓ Removed aliases file${NC}"
    fi
    
    echo -e "${GREEN}✓ Aliases removed successfully${NC}"
    echo -e "${YELLOW}Please restart your terminal or run: source ~/.bashrc${NC}"
}

# Function to list available aliases
list_aliases() {
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}        AVAILABLE ALIASES${NC}"
    echo -e "${BLUE}========================================${NC}\n"
    
    if [ -f "$ALIAS_FILE" ]; then
        grep -E "^alias [a-zA-Z]" "$ALIAS_FILE" | sed 's/alias //' | while read line; do
            local alias_name=$(echo "$line" | cut -d'=' -f1)
            local alias_cmd=$(echo "$line" | cut -d'=' -f2- | sed "s/'//g")
            printf "  ${GREEN}%-20s${NC} %s\n" "$alias_name" "$alias_cmd"
        done
    else
        echo -e "${YELLOW}No aliases file found. Run with --install first.${NC}"
    fi
}

# Function to show currently installed aliases
show_installed_aliases() {
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}        CURRENTLY INSTALLED ALIASES${NC}"
    echo -e "${BLUE}========================================${NC}\n"
    
    if grep -q "source ~/.bashrc_aliases" "$HOME/.bashrc" 2>/dev/null; then
        echo -e "${GREEN}Aliases are installed and sourced in .bashrc${NC}\n"
        
        # Show some sample aliases
        echo -e "${YELLOW}Sample aliases available:${NC}"
        echo "  sysmon    - System monitor"
        echo "  security  - Security audit"
        echo "  backup    - Backup manager"
        echo "  logs      - Log analyzer"
        echo "  users     - User manager"
        echo "  netscan   - Network scanner"
        echo "  diskclean - Disk cleaner"
        echo "  update    - System update"
        echo ""
        echo -e "${YELLOW}Run 'alias' to see all available aliases${NC}"
    else
        echo -e "${YELLOW}No aliases installed. Run with --install first.${NC}"
    fi
}

# Function to show categorized aliases
show_categorized_aliases() {
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}        CATEGORIZED ALIASES${NC}"
    echo -e "${BLUE}========================================${NC}\n"
    
    echo -e "${GREEN}System Monitoring:${NC}"
    echo "  sysmon    - Real-time system monitor"
    echo "  sysinfo   - Detailed system information"
    echo "  psmon     - Process monitor"
    echo ""
    
    echo -e "${GREEN}Backup & Security:${NC}"
    echo "  backup    - Backup manager"
    echo "  security  - Security audit"
    echo "  ports     - Check open ports"
    echo "  failed-logins - Check failed login attempts"
    echo ""
    
    echo -e "${GREEN}Log Analysis:${NC}"
    echo "  logs      - Log analyzer"
    echo "  log-error - Show only errors"
    echo "  log-warn  - Show only warnings"
    echo "  syslog    - Analyze syslog"
    echo ""
    
    echo -e "${GREEN}Network Tools:${NC}"
    echo "  netscan   - Network scanner"
    echo "  netmon    - Network monitor"
    echo "  myip      - Show public IP"
    echo "  portscan  - Full port scan"
    echo ""
    
    echo -e "${GREEN}Disk Management:${NC}"
    echo "  diskclean - Disk cleanup"
    echo "  diskusage - Disk usage analyzer"
    echo "  largest   - Find largest files"
    echo ""
    
    echo -e "${GREEN}File Management:${NC}"
    echo "  organizer - File organizer"
    echo "  organize-dl - Organize Downloads folder"
    echo ""
    
    echo -e "${GREEN}Navigation:${NC}"
    echo "  ..        - Go up one directory"
    echo "  ...       - Go up two directories"
    echo ""
    
    echo -e "${GREEN}System Updates:${NC}"
    echo "  update    - Update system"
    echo "  install   - Install package"
    echo "  autoremove - Remove unused packages"
    echo ""
}

# Main function
main() {
    case "$1" in
        -i|--install)
            install_aliases
            ;;
        -r|--remove)
            remove_aliases
            ;;
        -l|--list)
            list_aliases
            ;;
        -s|--show)
            show_installed_aliases
            ;;
        -c|--categorized)
            show_categorized_aliases
            ;;
        -b|--backup)
            backup_bashrc
            ;;
        -h|--help)
            show_categorized_aliases
            usage
            ;;
        *)
            echo -e "${YELLOW}No option specified. Showing help...${NC}\n"
            show_categorized_aliases
            usage
            ;;
    esac
}

# Run main function
main "$@"
